name: Checks

on:
  pull_request:

env:
  X_POETRY_VERSION: 1.8.3
  X_POETRY_INSTALL_CACHE_KEY: poetry-0

jobs:
  setup:
    strategy:
      fail-fast: true
      matrix:
        os: [ "ubuntu-latest" ]
        python-version: [ "3.9" ]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Load cached Poetry installation
        id: cached-poetry
        uses: actions/cache@v3
        with:
          path: ~/.local
          key: ${{ env.X_POETRY_INSTALL_CACHE_KEY }}

      - name: Install and configure Poetry
        if: steps.cached-poetry.outputs.cache-hit != 'true'
        uses: snok/install-poetry@v1
        with:
          version: ${{ env.X_POETRY_VERSION }}
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ hashFiles('poetry.lock') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          export PATH="${HOME}/.local/bin:${PATH}"
          poetry install --only dev

  test:
    needs: setup
    strategy:
      fail-fast: true
      matrix:
        os: [ "ubuntu-latest" ]
        python-version: [ "3.9" ]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Load cached Poetry installation
        id: cached-poetry
        uses: actions/cache@v3
        with:
          path: ~/.local
          key: ${{ env.X_POETRY_INSTALL_CACHE_KEY }}

      - name: Install and configure Poetry
        if: steps.cached-poetry.outputs.cache-hit != 'true'
        uses: snok/install-poetry@v1
        with:
          version: ${{ env.X_POETRY_VERSION }}
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Load cached venv
        uses: actions/cache@v3
        id: cache
        with:
          path: .venv
          key: venv-${{ hashFiles('poetry.lock') }}

      - name: Run code style check
        run: |
          export PATH="${HOME}/.local/bin:${PATH}"
          poetry run ruff format --check voice_pulse/

      - name: Run code lint
        run: |
          export PATH="${HOME}/.local/bin:${PATH}"
          poetry run ruff check voice_pulse/

      - name: Build project
        run: |
          export PATH="${HOME}/.local/bin:${PATH}"
          poetry build
